name: Hello World!

on: push

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say Hello
        run: |
          echo "Hello world!"
  now_it_is_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Now it is
        run: |
          date
  list_directory_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Directory List
        run: |
          ls